# Docker-compose example for running a 3-node cluster.
services:
  node1:
    build:
      context: ../../../
      dockerfile: ./Dockerfile
    container_name: node1
    command: ["./memstore-dynamic-members", "--raft-addr=node1:60061", "--web-server=0.0.0.0:8001"]
    ports:
      - "8001:8001"
    expose:
      - "8001"

  node2:
    build:
      context: ../../../
      dockerfile: ./Dockerfile
    container_name: node2
    command: ["./memstore-dynamic-members", "--raft-addr=node2:60062", "--web-server=0.0.0.0:8002", "--peer-addr=node1:60061"]
    ports:
      - "8002:8002"
    expose:
      - "8002"
    depends_on:
      - node1

  node3:
    build:
      context: ../../../
      dockerfile: ./Dockerfile
    container_name: node3
    command: ["./memstore-dynamic-members", "--raft-addr=node3:60063", "--web-server=0.0.0.0:8003", "--peer-addr=node1:60061"]
    ports:
      - "8003:8003"
    expose:
      - "8003"
    depends_on:
      - node2
